In [18]:
#Loading libraries 
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler 

In [9]:
data = pd.read_csv('data/processed_diabetes_data.csv')

In [25]:
class0 = data[data["readmitted"] == 0]
class1 = data[data["readmitted"] == 1]
majorityCount = class0.shape[0]
minorityCount = class1.shape[0]
class01, class02 = class0.sample(frac=0.1, random_state=42), class0.sample(frac=0.9, random_state=42)
print("Class 0 (readmitted = 0): ", majorityCount)
print("Class 1 (readmitted = 1): ", minorityCount)
print("20% Resampled Class 0 (readmitted = 0):", class01.shape[0])
print("Class 1 (readmitted= 1): ", minorityCount)

oversampled_class1 = class1.sample(frac=0.1, replace=True, random_state=42)
sampled_df = pd.concat([class01, oversampled_class1])
sampled_df.drop(columns=["Unnamed: 0"]).describe()

Class 0 (readmitted = 0):  90406
Class 1 (readmitted = 1):  11357
20% Resampled Class 0 (readmitted = 0): 9041
Class 1 (readmitted= 1):  11357


age  time_in_hospital  num_lab_procedures  num_procedures  \
count  10177.000000      10177.000000        10177.000000    10177.000000   
mean      65.985556          4.367004           43.134126        1.331041   
std       15.900063          2.943190           19.474766        1.723683   
min        5.000000          1.000000            1.000000        0.000000   
25%       55.000000          2.000000           32.000000        0.000000   
50%       65.000000          4.000000           44.000000        1.000000   
75%       75.000000          6.000000           57.000000        2.000000   
max       95.000000         14.000000          102.000000        6.000000   

       num_medications  number_outpatient  number_emergency  number_inpatient  \
count     10177.000000       10177.000000      10177.000000      10177.000000   
mean         16.036651           0.364253          0.192002          0.631424   
std           8.120029           1.229179          0.720927          1.253708   
min           1.000000           0.000000          0.000000          0.000000   
25%          10.000000           0.000000          0.000000          0.000000   
50%          15.000000           0.000000          0.000000          0.000000   
75%          20.000000           0.000000          0.000000          1.000000   
max          69.000000          38.000000         12.000000         16.000000   

       number_diagnoses    readmitted  ...  examide  citoglipton  \
count      10177.000000  10177.000000  ...  10177.0      10177.0   
mean           7.395991      0.111624  ...      0.0          0.0   
std            1.943385      0.314919  ...      0.0          0.0   
min            1.000000      0.000000  ...      0.0          0.0   
25%            6.000000      0.000000  ...      0.0          0.0   
50%            8.000000      0.000000  ...      0.0          0.0   
75%            9.000000      0.000000  ...      0.0          0.0   
max           16.000000      1.000000  ...      0.0          0.0   

            insulin  glyburide-metformin  glipizide-metformin  \
count  10177.000000         10177.000000         10177.000000   
mean       1.415054             1.007271             0.000098   
std        0.846098             0.086114             0.009913   
min        0.000000             1.000000             0.000000   
25%        1.000000             1.000000             0.000000   
50%        1.000000             1.000000             0.000000   
75%        2.000000             1.000000             0.000000   
max        3.000000             3.000000             1.000000   

       glimepiride-pioglitazone  metformin-rosiglitazone  \
count                   10177.0                  10177.0   
mean                        0.0                      0.0   
std                         0.0                      0.0   
min                         0.0                      0.0   
25%                         0.0                      0.0   
50%                         0.0                      0.0   
75%                         0.0                      0.0   
max                         0.0                      0.0   

       metformin-pioglitazone        change   diabetesMed  
count                 10177.0  10177.000000  10177.000000  
mean                      0.0      0.531984      0.770954  
std                       0.0      0.499000      0.420239  
min                       0.0      0.000000      0.000000  
25%                       0.0      0.000000      1.000000  
50%                       0.0      1.000000      1.000000  
75%                       0.0      1.000000      1.000000  
max                       0.0      1.000000      1.000000  

[8 rows x 45 columns]

In [26]:
data = sampled_df

In [27]:
X = data.drop('readmitted',axis=1)

y = data['readmitted']

train, test = train_test_split(data, test_size=0.8, random_state=42)
print('Train:', train.shape[0])
print('Test:', test.shape[0])

rf = RandomForestClassifier(n_estimators=51)
model = rf.fit(X, y)


rfe = RFE(model, n_features_to_select=100)
rfe.fit(X, y)
selected_features = X.columns[rfe.support_]
print('Selected Features:', len(selected_features))
print(selected_features)

Train: 2035
Test: 8142
Selected Features: 45
Index(['Unnamed: 0', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'number_diagnoses', 'race',
       'gender', 'admission_type_id', 'discharge_disposition_id',
       'admission_source_id', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum',
       'A1Cresult', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose',
       'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton',
       'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed'],
      dtype='object')


In [28]:
#all LGBM features

In [29]:
import lightgbm as lgb
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = data.drop('readmitted',axis=1)
y = data['readmitted']

# Define and fit a StandardScaler
scaler = StandardScaler()
model = scaler.fit(X)
scaled_X = model.transform(X)

# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.2, random_state=42, stratify=y)

# Define LightGBM parameters
params = {
    'objective': 'binary',
    'verbosity': -1,
    'is_unbalance': True,
    'learning_rate': 0.01
}

# Create and fit a LightGBM model
light = lgb.LGBMClassifier(**params)
light.fit(X_train, y_train)

# Feature selection using SelectFromModel
threshold = 'median'
feature_selector = SelectFromModel(light, threshold=threshold)
model = feature_selector.fit(X_train, y_train)

# Get the selected features
X_train_selected = model.transform(X_train)
selected_features_mask = feature_selector.get_support()

# Get feature importances
feature_importance = light.feature_importances_
feature_names = X.columns
# Create a DataFrame for feature importances
print(feature_names, feature_importance)

Index(['Unnamed: 0', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'number_diagnoses', 'race',
       'gender', 'admission_type_id', 'discharge_disposition_id',
       'admission_source_id', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum',
       'A1Cresult', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose',
       'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton',
       'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed'],
      dtype='object') [363  90 144 310  88 240  56  25 169  79  30  19  11  95  43 318 318 249
   8  68  21   0   0   0  13   0   7   9   0   7  17   0   0   0   0   0
   0  

In [30]:
#selected LGBM Features

In [31]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
from sklearn.metrics import accuracy_score, roc_auc_score
params = {
    'objective': 'binary',
    'verbosity': -1,
    'is_unbalance': True,
    'learning_rate': 0.01
}

# Create and fit a LightGBM model with all attributes
model_all_attributes = lgb.LGBMClassifier(**params)
model_all_attributes.fit(X_train, y_train)

# Predict on the test set
y_pred_all_attributes = model_all_attributes.predict(X_test)

# Evaluate the model with all attributes
accuracy_all_attributes = accuracy_score(y_test, y_pred_all_attributes)
roc_auc_all_attributes = roc_auc_score(y_test, model_all_attributes.predict_proba(X_test)[:, 1])
precision_all_attributes = precision_score(y_test, y_pred_all_attributes)
recall_all_attributes = recall_score(y_test, y_pred_all_attributes)
f1_all_attributes = f1_score(y_test, y_pred_all_attributes)

# Compute confusion matrix for the model with all attributes
confusion_matrix_all_attributes = confusion_matrix(y_test, y_pred_all_attributes)

print("Model with all attributes:")
print("Accuracy:", accuracy_all_attributes)
print("ROC AUC:", roc_auc_all_attributes)
print("Precision:", precision_all_attributes)
print("Recall:", recall_all_attributes)
print("F1 Score:", f1_all_attributes)
print("Confusion Matrix:\n", confusion_matrix_all_attributes)

# Create and fit a LightGBM model with the selected attributes
feature_selector = SelectFromModel(model_all_attributes, threshold='median')
X_train_selected = feature_selector.transform(X_train)
X_test_selected = feature_selector.transform(X_test)

model_selected_attributes = lgb.LGBMClassifier(**params)
model_selected_attributes.fit(X_train_selected, y_train)

# Predict on the test set
y_pred_selected_attributes = model_selected_attributes.predict(X_test_selected)

# Evaluate the model with selected attributes
accuracy_selected_attributes = accuracy_score(y_test, y_pred_selected_attributes)
roc_auc_selected_attributes = roc_auc_score(y_test, model_selected_attributes.predict_proba(X_test_selected)[:, 1])
precision_selected_attributes = precision_score(y_test, y_pred_selected_attributes)
recall_selected_attributes = recall_score(y_test, y_pred_selected_attributes)
f1_selected_attributes = f1_score(y_test, y_pred_selected_attributes)

# Compute confusion matrix for the model with selected attributes
confusion_matrix_selected_attributes = confusion_matrix(y_test, y_pred_selected_attributes)

print("\nModel with selected attributes:")
print("Accuracy:", accuracy_selected_attributes)
print("ROC AUC:", roc_auc_selected_attributes)
print("Precision:", precision_selected_attributes)
print("Recall:", recall_selected_attributes)
print("F1 Score:", f1_selected_attributes)
cm = confusion_matrix_selected_attributes
print("Confusion Matrix:\n", cm)


Model with all attributes:
Accuracy: 0.8796660117878192
ROC AUC: 0.6679853303234196
Precision: 0.23529411764705882
Recall: 0.03524229074889868
F1 Score: 0.06130268199233717
Confusion Matrix:
 [[1783   26]
 [ 219    8]]

Model with selected attributes:
Accuracy: 0.8796660117878192
ROC AUC: 0.6650935240586107
Precision: 0.23529411764705882
Recall: 0.03524229074889868
F1 Score: 0.06130268199233717
Confusion Matrix:
 [[1783   26]
 [ 219    8]]


In [32]:
#Using RFE Selected Feats

In [33]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
from sklearn.metrics import accuracy_score, roc_auc_score


X = data[selected_features]
y = data['readmitted']
X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.2, random_state=42, stratify=y)


params = {
    'objective': 'binary',
    'verbosity': -1,
    'is_unbalance': True,
    'learning_rate': 0.01
}

model_selected_attributes = lgb.LGBMClassifier(**params)
model_selected_attributes.fit(X_train, y_train)

# Predict on the test set
y_pred_selected_attributes = model_selected_attributes.predict(X_test)

# Evaluate the model with selected attributes
accuracy_selected_attributes = accuracy_score(y_test, y_pred_selected_attributes)
roc_auc_selected_attributes = roc_auc_score(y_test, model_selected_attributes.predict_proba(X_test)[:, 1])
precision_selected_attributes = precision_score(y_test, y_pred_selected_attributes)
recall_selected_attributes = recall_score(y_test, y_pred_selected_attributes)
f1_selected_attributes = f1_score(y_test, y_pred_selected_attributes)

# Compute confusion matrix for the model with selected attributes
confusion_matrix_selected_attributes = confusion_matrix(y_test, y_pred_selected_attributes)

print("\nModel with selected attributes:")
print("Accuracy:", accuracy_selected_attributes)
print("ROC AUC:", roc_auc_selected_attributes)
print("Precision:", precision_selected_attributes)
print("Recall:", recall_selected_attributes)
print("F1 Score:", f1_selected_attributes)
cm = confusion_matrix_selected_attributes
print("Confusion Matrix:\n", cm)



Model with selected attributes:
Accuracy: 0.8796660117878192
ROC AUC: 0.6679853303234196
Precision: 0.23529411764705882
Recall: 0.03524229074889868
F1 Score: 0.06130268199233717
Confusion Matrix:
 [[1783   26]
 [ 219    8]]
